# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TikTok Trending Data Scraper

on:
  push:
    branches: [ data ]
  pull_request:
    branches: [ data ]
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  cron:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: rm -rf ./data
    - run: mkdir data
    - run: npm install --if-present
    - run: npm start

    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: GPG user IDs
      run: |
        echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
        echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
        echo "name:        ${{ steps.import-gpg.outputs.name }}"
        echo "email:       ${{ steps.import-gpg.outputs.email }}"

    - name: Commit +sign commit and push changes
      run: |-
        git config --global user.email "${{ steps.import-gpg.outputs.email }}"
        git config --global user.name "${{ steps.import-gpg.outputs.name }}"
        git add -A
        timestamp=$(date '+%F %H:%M:%S %Z')
        git commit -m "Tiktok-TDS: Update Tiktok Trending Data ${timestamp}" || exit 0
        git push
